include('../../platform/development/services/Tiltfile')
include('../../../../config-service/Tiltfile')
include('../../../../catalog-service/Tiltfile')
include('../../../../order-service/Tiltfile')

update_settings(max_parallel_updates=4)