services:
  example-postgres:
    image: "postgres:15.1"
    container_name: "example-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql