services:

  example-postgres:
    image: "postgres:15.1"
    container_name: "example-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql

  example-redis:
    image: "redis:7.0"
    container_name: "example-redis"
    ports:
      - 6379:6379

  example-rabbitmq:
    image: rabbitmq:3.11.6-management
    container_name: example-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf